### ISSUE TITLE
April 2022 Tracking

### ISSUE THREAD

**Issue by AngelOnFira** [rust-lang/ctcft#33]
This is the agenda for April 2022, the theme is "learning"

Related issues:

- #29 

Todo:
- [ ] Calendar invites
- [ ] Initial CTCFT post
- [ ] Reach out to speakers
- [ ] Agenda CTCFT post update (#32)
- [ ] Inside Rust post
- [ ] Agenda Tweet
- [ ] Reminder Tweet day of
- [ ] Post recording
